name: health_tracker
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  loader_overlay: ^4.0.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  chat_bubbles: ^1.6.0
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/icon.jpg"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - assets/bg_img/bg1.jpg
