// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVxJBjVxqOOXdkk51SxPvuqiUWdk3r5AY',
    appId: '1:1002862491808:web:5a85a809a0ad69932ab1c5',
    messagingSenderId: '1002862491808',
    projectId: 'health-tracker-58801',
    authDomain: 'health-tracker-58801.firebaseapp.com',
    storageBucket: 'health-tracker-58801.appspot.com',
    measurementId: 'G-KPK6VCFXNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIUQ7PabGQE5UCJeMe7TNswnYAAPETzU',
    appId: '1:1002862491808:android:ecc9e8cae50555082ab1c5',
    messagingSenderId: '1002862491808',
    projectId: 'health-tracker-58801',
    storageBucket: 'health-tracker-58801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1v4b0vZr-S5BKk68ml87OGrnlDhZpAcU',
    appId: '1:1002862491808:ios:730364f54fef92492ab1c5',
    messagingSenderId: '1002862491808',
    projectId: 'health-tracker-58801',
    storageBucket: 'health-tracker-58801.appspot.com',
    iosBundleId: 'com.example.healthTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1v4b0vZr-S5BKk68ml87OGrnlDhZpAcU',
    appId: '1:1002862491808:ios:730364f54fef92492ab1c5',
    messagingSenderId: '1002862491808',
    projectId: 'health-tracker-58801',
    storageBucket: 'health-tracker-58801.appspot.com',
    iosBundleId: 'com.example.healthTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVxJBjVxqOOXdkk51SxPvuqiUWdk3r5AY',
    appId: '1:1002862491808:web:97b8329f47c71d632ab1c5',
    messagingSenderId: '1002862491808',
    projectId: 'health-tracker-58801',
    authDomain: 'health-tracker-58801.firebaseapp.com',
    storageBucket: 'health-tracker-58801.appspot.com',
    measurementId: 'G-PJH6Q6RVXR',
  );
}
